[build]
  publish = ".next"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "22"

# Performance optimizations
[[headers]]
  for = "/*"
  [headers.values]
    # Security headers
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "origin-when-cross-origin"
    
    # Performance headers
    X-DNS-Prefetch-Control = "on"

# HTML files should not be cached aggressively
[[headers]]
  for = "/*.html"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

[[plugins]]
  package = "@netlify/plugin-nextjs"